Repository rimo030/nestjs-e-commerce-frame, pull requests merged in 2023-11, with the labels that each got.

#16 PullRequest template을 제공합니다.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Convension

#27 전체 도메인에 대해 Entity 를 작성하였습니다!
  data-source.ts
  package-lock.json
  package.json
  src/entities/board.entity.ts
  src/entities/cart-input-option.entity.ts
  src/entities/cart-option.entity.ts
  src/entities/cart-product-input-option.entity.ts
  src/entities/cart-product-option.entity.ts
  src/entities/cart-product-required-option.entity.ts
  src/entities/cart-required-option.entity.ts
  src/entities/cart.entity.ts
  src/entities/category.entity.ts
  src/entities/company.entity.ts
  src/entities/order-prodect-riquired-option.entity.ts
  src/entities/order-product-bundle.entity.ts
  src/entities/order-product-input-option.entity.ts
  src/entities/order-product-option.entity.ts
  src/entities/order-product-riquired-option.entity.ts
  src/entities/order-product.entity.ts
  src/entities/order.entity.ts
  src/entities/product-bundle.entity.ts
  src/entities/product-input-option.entity.ts
  src/entities/product-option.entity.ts
  src/entities/product-required-option.entity.ts
  src/entities/product.entity.ts
  src/entities/seller.entity.ts
  src/entities/user.entity.ts
Labels: DB, ERD

#62 테스트 코드 예시 추가 ( 회사, 카테고리, 상품 일부 )
  src/test/unit/cart.spec.ts
  src/test/unit/category.spec.ts
  src/test/unit/company.spec.ts
  src/test/unit/product.spec.ts
Labels: BE, Domain
